// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8GQkdoyC7Gwq3DRiUxgcdKjlFNM7e8L4',
    appId: '1:654964234129:web:41d8c3ed0c3c6f5d346c30',
    messagingSenderId: '654964234129',
    projectId: 'login-flutter-test-4aa9c',
    authDomain: 'login-flutter-test-4aa9c.firebaseapp.com',
    storageBucket: 'login-flutter-test-4aa9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaISc6v1g4ufS4RAqRU40d8LukW5Qhiew',
    appId: '1:654964234129:android:bb86ec29452e6b6e346c30',
    messagingSenderId: '654964234129',
    projectId: 'login-flutter-test-4aa9c',
    storageBucket: 'login-flutter-test-4aa9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHTOifk2Rq7Z2i1vEi5njdIpmO9UuzhVw',
    appId: '1:654964234129:ios:739301ef738caa4e346c30',
    messagingSenderId: '654964234129',
    projectId: 'login-flutter-test-4aa9c',
    storageBucket: 'login-flutter-test-4aa9c.appspot.com',
    iosClientId: '654964234129-l8t1dtkvail7k1ap2kph7rppgmjp7m32.apps.googleusercontent.com',
    iosBundleId: 'com.miraclestudios.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHTOifk2Rq7Z2i1vEi5njdIpmO9UuzhVw',
    appId: '1:654964234129:ios:739301ef738caa4e346c30',
    messagingSenderId: '654964234129',
    projectId: 'login-flutter-test-4aa9c',
    storageBucket: 'login-flutter-test-4aa9c.appspot.com',
    iosClientId: '654964234129-l8t1dtkvail7k1ap2kph7rppgmjp7m32.apps.googleusercontent.com',
    iosBundleId: 'com.miraclestudios.loginFirebase',
  );
}
